openapi: 3.2.0
info:
  title: Researchers Resources API
  description: API for Resources for Researchers
  version: 1.0.0
servers:
- url: /r4r/v1
tags:
- name: Resources
paths:
  /resources:
    get:
      tags:
      - Resources
      summary: Searches all resources
      operationId: Resources_GetAll
      parameters:
      - name: q
        x-originalName: keyword
        in: query
        description: Full-text search keyword
        schema:
          type:
          - string
          - 'null'
        x-position: 1
      - name: toolTypes
        in: query
        style: form
        explode: true
        description: One or more toolTypes keys to filter by
        schema:
          type:
          - array
          - 'null'
          items:
            type: string
        x-position: 2
      - name: toolSubtypes
        x-originalName: subTypes
        in: query
        style: form
        explode: true
        description: One or more toolSubtypes keys to filter by
        schema:
          type:
          - array
          - 'null'
          items:
            type: string
        x-position: 3
      - name: researchAreas
        in: query
        style: form
        explode: true
        description: One or more researchArea keys to filter by
        schema:
          type:
          - array
          - 'null'
          items:
            type: string
        x-position: 4
      - name: researchTypes
        in: query
        style: form
        explode: true
        description: One or more researchTypes keys to filter by
        schema:
          type:
          - array
          - 'null'
          items:
            type: string
        x-position: 5
      - name: docs
        in: query
        style: form
        explode: true
        description: 'One or more Divisions, Offices, and Centers (DOCs) to filter by '
        schema:
          type:
          - array
          - 'null'
          items:
            type: string
        x-position: 6
      - name: include
        x-originalName: includeFields
        in: query
        style: form
        explode: true
        description: Resource fields to include. (When empty all are returned)
        schema:
          type:
          - array
          - 'null'
          items:
            type: string
        x-position: 7
      - name: includeFacets
        in: query
        style: form
        explode: true
        description: Available Facets to return. (When empty all are returned)
        schema:
          type:
          - array
          - 'null'
          items:
            type: string
        x-position: 8
      - name: size
        x-originalName: strSize
        in: query
        description: The number of resources to return
        schema:
          type:
          - string
          - 'null'
        x-position: 9
      - name: from
        x-originalName: strFrom
        in: query
        description: The offset of the resources to return
        schema:
          type:
          - string
          - 'null'
        x-position: 10
      responses:
        '200':
          description: The Resources and available facets that match the query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceResults'
components:
  schemas:
    PageMetaData:
      type: object
      description: Describes the page metadata for returned resource results
      additionalProperties: false
      properties:
        totalResults:
          type: integer
          description: The total number of resources returned
          format: int32
        from:
          type: integer
          description: The offset that the results start from
          format: int32
        originalQuery:
          type:
          - string
          - 'null'
          description: The original query, for which the resource results are returned
    Resource:
      type: object
      description: Describes the information about a resource
      additionalProperties: false
      properties:
        id:
          type: integer
          description: The resource identifier
          format: int32
        title:
          type:
          - string
          - 'null'
          description: The title of the resource
        website:
          type:
          - string
          - 'null'
          description: The URL where you can get more information about the resource
        body:
          type:
          - string
          - 'null'
          description: The detailed description of the resource
        description:
          type:
          - string
          - 'null'
          description: A brief description of the resource
        toolTypes:
          type:
          - array
          - 'null'
          description: A list of the tool types this resource is categorized as
          items:
            $ref: '#/components/schemas/KeyLabel'
        toolSubtypes:
          type:
          - array
          - 'null'
          description: A list of the sub tool types this resource is categorized as
          items:
            $ref: '#/components/schemas/ToolSubtype'
        researchAreas:
          type:
          - array
          - 'null'
          description: A list of the areas of research areas where this resource applies
          items:
            $ref: '#/components/schemas/KeyLabel'
        researchTypes:
          type:
          - array
          - 'null'
          description: A list of the areas of research types where this resource applies
          items:
            $ref: '#/components/schemas/KeyLabel'
        resourceAccess:
          description: Information about how one can aquire access to the resource
          oneOf:
          - $ref: '#/components/schemas/ResourceAccess'
        doCs:
          type:
          - array
          - 'null'
          description: A list of the NCI Divisions, Offices and Centers (DOCs) that manage the resource
          items:
            $ref: '#/components/schemas/KeyLabel'
        poCs:
          type:
          - array
          - 'null'
          description: A list of points of contact for the resource
          items:
            $ref: '#/components/schemas/Contact'
    KeyLabel:
      type: object
      description: Describes an item's key and label
      additionalProperties: false
      properties:
        key:
          type:
          - string
          - 'null'
          description: The key of the item
        label:
          type:
          - string
          - 'null'
          description: The label of the item
    FacetItem:
      type: object
      description: Describes the information about a facet item
      additionalProperties: false
      properties:
        key:
          type:
          - string
          - 'null'
          description: The key of the facet item
        label:
          type:
          - string
          - 'null'
          description: The label of the facet item
        count:
          type: integer
          description: The count of the facet item (number of items categorized as this facet item)
          format: int32
        selected:
          type: boolean
          description: Whether or not this facet item is selected
    ResourceResults:
      type: object
      description: Describes the information about the returned results
      additionalProperties: false
      properties:
        meta:
          description: The page metadata about the returned results
          oneOf:
          - $ref: '#/components/schemas/PageMetaData'
        results:
          type:
          - array
          - 'null'
          description: a list of resources returned that match the query
          items:
            $ref: '#/components/schemas/Resource'
        facets:
          type:
          - array
          - 'null'
          description: A list of facets returned that match the query
          items:
            $ref: '#/components/schemas/Facet'
    Contact:
      type: object
      description: Describes the information about a point of contact
      additionalProperties: false
      properties:
        name:
          description: The name of the contact
          oneOf:
          - $ref: '#/components/schemas/Name'
        title:
          type:
          - string
          - 'null'
          description: The title of the contact
        phone:
          type:
          - string
          - 'null'
          description: The phone number of the contact
        email:
          type:
          - string
          - 'null'
          description: The email of the contact
    ToolSubtype:
      allOf:
      - $ref: '#/components/schemas/KeyLabel'
      - type: object
        description: Describes the information about the tool type of an resource
        additionalProperties: false
        properties:
          parentKey:
            type:
            - string
            - 'null'
            description: The parent key of a tool subtype
    Name:
      type: object
      description: Contains the information about a name of a point of contact
      additionalProperties: false
      properties:
        prefix:
          type:
          - string
          - 'null'
          description: The name prefix of the contact
        firstName:
          type:
          - string
          - 'null'
          description: The first name of the contact
        middleName:
          type:
          - string
          - 'null'
          description: The middle name of the contact
        lastName:
          type:
          - string
          - 'null'
          description: The last name of the contact
        suffix:
          type:
          - string
          - 'null'
          description: The name suffix of the contact
    Facet:
      type: object
      description: Describes the information about a facet
      additionalProperties: false
      properties:
        title:
          type:
          - string
          - 'null'
          description: The title of the facet
        param:
          type:
          - string
          - 'null'
          description: The param name for the facet
        items:
          type:
          - array
          - 'null'
          description: A list of facet items within this facet
          items:
            $ref: '#/components/schemas/FacetItem'
    ResourceAccess:
      type: object
      description: Describes the information about the resource access of a resource
      additionalProperties: false
      properties:
        type:
          type:
          - string
          - 'null'
          description: The type of resource access
        notes:
          type:
          - string
          - 'null'
          description: The notes about the resource access
x-generator: NSwag v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0))
